Repository Hansung-WebFramework/frontend, pull requests merged in 2024-11, with the labels that each got.

#9 feat: 분석 차트 페이지 구현 완료
  react-app/package-lock.json
  react-app/package.json
  react-app/public/mockServiceWorker.js
  react-app/src/App.jsx
  react-app/src/assets/images/fakenewsimg.png
  react-app/src/components/layout/AnalysisPage.module.css
  react-app/src/components/layout/Header.jsx
  react-app/src/components/layout/Header.module.css
  react-app/src/components/layout/Navbar.jsx
  react-app/src/components/ui/Button.jsx
  react-app/src/components/ui/Card.jsx
  react-app/src/index.css
  react-app/src/main.jsx
  react-app/src/pages/AnalysisPage.jsx
  react-app/tailwind.config.js
Labels: ☘️ 지운, 🚀 Feat

#12 Feat/#3
  react-app/package-lock.json
  react-app/src/main.jsx
  react-app/src/mocks/analysis.json
  react-app/src/mocks/handlers.js
  react-app/src/pages/AnalysisPage.jsx
Labels: ☘️ 지운, 🏷 Fix

#15 feat: Loader 애니메이션 추가
  react-app/src/components/Loader.jsx
  react-app/src/components/LoaderStyle.css
  react-app/src/components/layout/AnalysisPage.module.css
  react-app/src/pages/AnalysisPage.jsx
Labels: ☘️ 지운, 🚀 Feat

#16 feat: 신뢰도 50% 미만 기사 경고창 띄우기
  react-app/src/components/ErrorAlert.jsx
  react-app/src/components/ErrorAlert.module.css
  react-app/src/mocks/analysis.json
  react-app/src/pages/AnalysisPage.jsx
Labels: ☘️ 지운, 🚀 Feat

#17 feat: Accuracy Wave 구현 완료
  react-app/src/components/AccuracyCircle.css
  react-app/src/components/AccuracyCircle.jsx
  react-app/src/pages/AnalysisPage.jsx
Labels: ☘️ 지운, 🚀 Feat

#19 [feat] 판별된 기사 목록 페이지 구현
  react-app/public/mockServiceWorker.js
  react-app/src/App.jsx
  react-app/src/assets/images/IdentifiedArticlesPage1.jsx
  react-app/src/components/articles/ArticleItem.jsx
  react-app/src/components/articles/ArticleList.jsx
  react-app/src/components/articles/Pagination.jsx
  react-app/src/components/articles/SelectedArticle.jsx
  react-app/src/data/articles.js
  react-app/src/mocks/analysis.json
  react-app/src/pages/AnalysisPage.jsx
  react-app/src/pages/IdentifiedArticlesPage.jsx
Labels: 🚀 Feat, 🎶 동영

#21 [feat] 검색 페이지 구현
  react-app/src/App.jsx
  react-app/src/components/articles/ArticleItem.jsx
  react-app/src/components/layout/Navbar.jsx
  react-app/src/pages/IdentifiedArticlesPage.jsx
  react-app/src/pages/SearchResultsPage.jsx
Labels: 🚀 Feat, 🎶 동영
